[package]
name = "cg3-stream-parser"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"

